### ISSUE TITLE
Unified Docker Environment

### ISSUE THREAD

**Issue by codeJRV** [GoCorona-org/Backend#13]
Create a unified docker container ( host on dockerhub ) and submit a docker file that can run all dependencies and servers of the project

**Comment by wadkar** [comment]
#22 has docker-compose and respective dockerfiles for the project. Please follow [this guide](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html) to setup your local environment if you didn't README

We don't need to host it on dockerhub (yet)
