### ISSUE TITLE
JSON Format Mismatch for Intersection Calculator

### ISSUE THREAD

**Issue by nightblade23** [GoCorona-org/Backend#29]
Currently the endpoint for intersection calculator is corona_app/
The code which is present in Sanjana's branch accepts the JSON data in below format

> {
    "name": "a",
    "status": 0,
    "latitude": 0.0,
    "longitude": 0.0,
    "diabetes": false
}

The document which is [present](https://github.com/GoCorona-org/Backend/blob/master/docs/location_history.md) accepts the JSON data in the below format

> {
   "id": "p1",
   "location_history": [
      {
         "timeslot": "00.00.01.15.2020",
         "lat": "123456",
         "long": "123456",
         "status": "unknown"
      },
      {
         "timeslot": "00.10.01.15.2020",
         "lat": "123456",
         "long": "123456",
         "status": "unknown"
      }
   ]
}

Would like to have the format for the JSON backend as per the document.

**Comment by sanjanamoha** [comment]
This was resolved.
