### ISSUE TITLE
Need a separate API for Travel Questionnaire

### ISSUE THREAD

**Issue by theTechie** [GoCorona-org/Backend#31]
Looking at the `/corona_app/medmap`, it looks like all the travel questions are also integrated into the same API. 

But, as per the UI designs, travel questions are grouped separately; so we will need a separate API which we will POST to with answers to all travel-related questions.

![image](https://user-images.githubusercontent.com/1046486/80011318-549c5780-84e9-11ea-9fce-c1996b7ddfb4.png)

**Comment by theTechie** [comment]
@sanjanamoha @wadkar @Aakashv6 @codeJRV

**Comment by sanjanamoha** [comment]
A separate endpoint for the travel questionnaire was created at "/medmap/{med_uuid}" URL with a PUT request.
