### ISSUE TITLE
Am I Exposed API

### ISSUE THREAD

**Issue by theTechie** [GoCorona-org/Backend#32]
What is the endpoint for this API?

`GET api.gocorona.org/AmIExposed/<patient_id>`

returns { exposed: True } or { exposed: False } from the server

@sanjanamoha @wadkar @Aakashv6 @codeJRV

**Comment by sanjanamoha** [comment]
{Exposure: unknown},
{Exposure: exposed},
{Exposure: positive},

The above values are returned at "amIExposed/<str:uuid>" endpoint
